### ISSUE TITLE
lumen5.6   Error: Call to undefined method Laravel\Lumen\Application::getProvider()

### ISSUE THREAD

**Issue by gamelife1314** [php-pm/php-pm-httpkernel#105]
```
string(4263) "Error: Call to undefined method Laravel\Lumen\Application::getProvider() in /var/www/vendor/php-pm/httpkernel-adapter/Bootstraps/Laravel.php:128
Stack trace:
#0 /var/www/vendor/php-pm/httpkernel-adapter/Bootstraps/Laravel.php(119): PHPPM\Bootstraps\Laravel->resetProvider('\\Illuminate\\Coo...')
#1 /var/www/vendor/php-pm/httpkernel-adapter/Bridges/HttpKernel.php(113): PHPPM\Bootstraps\Laravel->postHandle(Object(Laravel\Lumen\Application))
#2 /var/www/vendor/php-pm/php-pm/src/ProcessSlave.php(431): PHPPM\Bridges\HttpKernel->handle(Object(React\Http\Io\ServerRequest))
#3 /var/www/vendor/php-pm/php-pm/src/ProcessSlave.php(392): PHPPM\ProcessSlave->handleRequest(Object(React\Http\Io\ServerRequest))
#4 /var/www/vendor/react/http/src/Io/MiddlewareRunner.php(49): PHPPM\ProcessSlave->onRequest(Object(React\Http\Io\ServerRequest))
#5 /var/www/vendor/react/http/src/Io/MiddlewareRunner.php(54): React\Http\Io\MiddlewareRunner->call(Object(React\Http\Io\ServerRequest), 3)
#6 /var/www/vendor/react/http/src/Middleware/RequestBodyParserMiddleware.php(34): React\Http\Io\MiddlewareRunner->React\Http\Io\{closure}(Object(React\Http\Io\ServerRequest))
#7 /var/www/vendor/react/http/src/Io/MiddlewareRunner.php(59): React\Http\Middleware\RequestBodyParserMiddleware->__invoke(Object(React\Http\Io\ServerRequest), Object(Closure))
#8 /var/www/vendor/react/http/src/Io/MiddlewareRunner.php(54): React\Http\Io\MiddlewareRunner->call(Object(React\Http\Io\ServerRequest), 2)
#9 /var/www/vendor/react/http/src/Middleware/RequestBodyBufferMiddleware.php(44): React\Http\Io\MiddlewareRunner->React\Http\Io\{closure}(Object(React\Http\Io\ServerRequest))
#10 /var/www/vendor/react/http/src/Io/MiddlewareRunner.php(59): React\Http\Middleware\RequestBodyBufferMiddleware->__invoke(Object(React\Http\Io\ServerRequest), Object(Closure))
#11 /var/www/vendor/react/http/src/Io/MiddlewareRunner.php(54): React\Http\Io\MiddlewareRunner->call(Object(React\Http\Io\ServerRequest), 1)
#12 /var/www/vendor/react/http/src/Middleware/LimitConcurrentRequestsMiddleware.php(91): React\Http\Io\MiddlewareRunner->React\Http\Io\{closure}(Object(React\Http\Io\ServerRequest))
#13 /var/www/vendor/react/http/src/Io/MiddlewareRunner.php(59): React\Http\Middleware\LimitConcurrentRequestsMiddleware->__invoke(Object(React\Http\Io\ServerRequest), Object(Closure))
#14 /var/www/vendor/react/http/src/Io/MiddlewareRunner.php(40): React\Http\Io\MiddlewareRunner->call(Object(React\Http\Io\ServerRequest), 0)
#15 /var/www/vendor/react/http/src/StreamingServer.php(237): React\Http\Io\MiddlewareRunner->__invoke(Object(React\Http\Io\ServerRequest))
#16 /var/www/vendor/react/http/src/StreamingServer.php(176): React\Http\StreamingServer->handleRequest(Object(React\Socket\Connection), Object(React\Http\Io\ServerRequest))
#17 /var/www/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\StreamingServer->React\Http\{closure}(Object(React\Http\Io\ServerRequest), '')
#18 /var/www/vendor/react/http/src/Io/RequestHeaderParser.php(59): Evenement\EventEmitter->emit('headers', Array)
#19 /var/www/vendor/react/http/src/Io/RequestHeaderParser.php(47): React\Http\Io\RequestHeaderParser->parseAndEmitRequest(134)
#20 /var/www/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\RequestHeaderParser->feed('GET / HTTP/1.1\r...')
#21 /var/www/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#22 /var/www/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('GET / HTTP/1.1\r...')
#23 /var/www/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit('data', Array)
#24 [internal function]: React\Stream\DuplexResourceStream->handleData(Resource id #241, Object(React\EventLoop\StreamSelectLoop))
#25 /var/www/vendor/react/event-loop/src/StreamSelectLoop.php(236): call_user_func(Array, Resource id #241, Object(React\EventLoop\StreamSelectLoop))
#26 /var/www/vendor/react/event-loop/src/StreamSelectLoop.php(205): React\EventLoop\StreamSelectLoop->waitForStreamActivity(89881)
#27 /var/www/vendor/php-pm/php-pm/src/ProcessSlave.php(351): React\EventLoop\StreamSelectLoop->run()
#28 /tmp/dbgabPHPj(36): PHPPM\ProcessSlave->run()
#29 {main}"
```

**Comment by andig** [comment]
Could you check if this works for you: https://github.com/php-pm/php-pm-httpkernel/pull/99/files

**Comment by andig** [comment]
Closing due to missing feedback.
