### ISSUE TITLE
Symfony2.8 AppKernel not found

### ISSUE THREAD

**Issue by kamillo1888** [php-pm/php-pm-httpkernel#30]
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Class 'AppKernel' not found in /home/kamil/Projekty/test/vendor/php-pm/httpkernel-adapter/Bootstraps/Symfony.php:58
Stack trace:
#0 /home/kamil/Projekty/test/vendor/php-pm/httpkernel-adapter/Bridges/HttpKernel.php(52): PHPPM\Bootstraps\Symfony->getApplication()
#1 /home/kamil/Projekty/test/vendor/php-pm/php-pm/ProcessSlave.php(177): PHPPM\Bridges\HttpKernel->bootstrap('\\PHPPM\\Bootstra...', 'dev', true)
#2 /home/kamil/Projekty/test/vendor/php-pm/php-pm/ProcessSlave.php(260): PHPPM\ProcessSlave->bootstrap('symfony', 'dev', true)
#3 /home/kamil/Projekty/test/vendor/php-pm/php-pm/ProcessCommunicationTrait.php(26): PHPPM\ProcessSlave->commandBootstrap(Array, Object(React\Socket\Connection))
#4 /home/kamil/Projekty/test/vendor/php-pm/php-pm/ProcessCommunicationTrait.php(50): PHPPM\ProcessSlave->processMessage('{"cmd":"bootstr...', Object(React\Socket\Connection))
#5 [internal function]: PHPPM\ProcessSlave->PHPPM\{ in /home/kamil/Projekty/test/vendor/php-pm/httpkernel-adapter/Bootstraps/Symfony.php on line 58

```

**Comment by marcj** [comment]
But you have an \AppKernel class?

**Comment by kamillo1888** [comment]
Yeah... for 2.8 you should require:
`app/bootstrap.php.cache`
then
`app/AppKernel.php`

And all works fine...

**Comment by marcj** [comment]
Well, I don't think so. I'm using 2.8 as well and it works. Maybe your autoloader is not correctly configured

**Comment by kamillo1888** [comment]
https://github.com/php-pm/php-pm-httpkernel/pull/31
Fixes all problems :+1:
